{% set name = "pyroll-core" %}
{% set version = "3.0.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyroll_core-{{ version }}.tar.gz
  sha256: 79fbc58b9e8426e5855e992747cb7f3c4e1cbed1c283e9ea4f1ec22712a9f58e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0,<3.dev0
    - scipy >=1.13,<2.dev0
    - shapely >=2.0.6,<3.0
    - ezdxf

test:
  imports:
    - pyroll.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyroll.readthedocs.io
  summary: PyRoll rolling simulation framework - core library.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
